// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iBeacon_simpleFingerprint
{
	public partial class ResultImageCell : UICollectionViewCell
	{
		public ResultImageCell (IntPtr handle) : base (handle)
		{
		}
	}
}
